config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    unlocks: 'usuarios/unlocks',
    passwords: 'usuarios/passwords',
    confirmations: 'usuarios/confirmations',
    omniauthable: 'usuarios/omniauths_callbacks'
  }
  #Rutas para inicio de sesión de administradores
  #Como el inicio lo haremos en un boton dentro de la barra de navegación, no haremos un get sino solamente un post y delete
  #get "/",                to: "sesiones#login", as: "login"
  post "sesiones",        to: "sesiones#iniciar_sesion",     as: "iniciar_sesion"
  delete "sesiones",      to: "sesiones#cerrar_sesion",      as: "cerrar_sesion"
  
  root 'paginas#inicio'
  get 'carrito',          to: 'paginas#carro',          as: 'carrito'

  

  #carros
  post 'carros/:producto_id',             to: 'carros#agregar_producto',        as: 'agregar_producto'
  put 'carros/:producto_id/cantidad',    to: 'carros#aumentar_un_producto',    as: 'aumentar_producto'
  delete 'carros/:id_producto',           to: 'carros#eliminar_producto',       as:'eliminar_producto'
  delete 'carros/:id_producto/cantidad',  to: 'carros#disminuir_un_producto',   as:'disminuir_producto'
  
  
  
  #delete 'productos/:id',      to: 'productos#eliminar'  no lo utilizamos por la razon explicada en el controlador.


  #delete especial para borrar sólo una foto
  

  


  get 'pedidos',                    to: 'pedidos#crear',            as: 'nuevo_pedido'
  get 'pagar',                      to: 'pedidos#pagar',            as: 'pagar'
  get 'pedidos/lista_pedidos',      to: 'pedidos#lista_pedidos',    as: 'lista_pedidos'
  get 'pedidos/detalles_pedidos',   to: 'pedidos#detalles_pedidos', as: 'detalles_pedidos' 

  post 'pedidos',             to: 'pedidos#guardar',    as: 'crear_pedido_cliente'

  namespace :admin do
    get "categorias",                                     to: "categorias#index",       as: "categorias"
    get "categorias/crear",                               to: "categorias#crear",       as: "nueva_categoria"
    get "categorias/:id",                                 to: "categorias#mostrar",     as: "categoria"
    get "categorias/:id/editar",                          to: "categorias#editar",      as: "editar_categorias"

    post "categorias/guardar",                            to: "categorias#guardar"
    put "categorias/:id",                                 to: "categorias#actualizar"
    patch "categorias/:id",                               to: "categorias#actualizar"
    delete "categorias/:id",                              to: "categorias#eliminar"

    get "productos",                                      to: "productos#index",        as: "productos"
    get "productos/crear",                                to: "productos#crear",        as: "nuevo_producto"
    get "productos/:id",                                  to: "productos#mostrar",      as: "producto"
    get "productos/:id/editar",                           to: "productos#editar",       as: "editar_productos"

    post "productos/guardar",                             to: "productos#guardar"
    put "productos/:id",                                  to: "productos#actualizar"
    patch "productos/:id",                                to: "productos#actualizar"
    delete "productos/:id/imagenes/:id_imagen",           to: "productos#eliminar_foto", as: "eliminar_foto"

    get "destinos",                                       to: "destinos#listar",        as: "destinos"
    get "destinos/crear",                                 to: "destinos#crear",         as: "nuevo_destino"
    get "destinos/:id",                                   to: "destinos#mostrar",       as: "destino"
    get "destinos/:id/editar",                            to: "destinos#editar",        as: "editar_destinos"

    post "destinos/guardar",                              to: "destinos#guardar"
    put "destinos/:id",                                   to: "destinos#actualizar"
    patch "destinos/:id",                                 to: "destinos#actualizar"
    delete "destinos/:id",                                to: "destinos#eliminar"

    get "/",                                              to: "pedidos#listar",         as: "pedidos"
    #get "pedidos",                                        to: "pedidos#crear",          as: "nuevo_pedido"
    get "pedidos/:id",                                    to: "pedidos#mostrar",        as: "pedido"
    get "pedidos/:id/editar",                             to: "pedidos#editar",         as: "editar_pedido"
    get "pagar",                                          to: "pedidos#pagar",          as: "pagar"

    post "pedidos",                                       to: "pedidos#crear",        as: "pedidos_helper_pedidos_formularios"
    put "pedidos/:id",                                    to: "pedidos#actualizar"     
    patch "pedidos/:id",                                  to: "pedidos#actualizar",     as: "pedidos_helper_pedidos_formulario"
    delete "pedidos/:id",                                 to: "pedidos#eliminar"

    # rutas para crear un producto ded un pedido
    get "pedidos/:id/productos",                              to: "pedidos#agregar_producto",             as: "agregar_producto"
    post "pedidos/:id/productos/:id_producto",                to: "pedidos#guardar_producto",             as: "guardar_producto"
    put "pedidos/:id/productos/:id_producto",                 to: "pedidos#aumentar_cantidad_producto",   as: "aumentar_producto"
    delete "pedidos/:id/productos/:id_producto",              to: "pedidos#disminuir_cantidad_producto",  as: "disminuir_producto"
    delete "pedidos/:id/productos/:id_producto/eliminar",     to: "pedidos#eliminar_producto",            as: "eliminar_producto"

    
        
  end

end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :destino, optional: true
  belongs_to :datos_envio
  belongs_to :estados_pedido

  has_one :ventas
  has_many :detalles_pedidos
  has_many :productos, through: :detalles_pedidos
  
end

app/controllers/admin/pedidos_controller.rb
class Admin::PedidosController < Admin::AdminController
    
    include Admin::PedidosHelper

    before_action :asignar_pedido, only: [:mostrar, :editar, :actualizar, :aumentar_cantidad_producto, :disminuir_cantidad_producto, :eliminar_producto, :agregar_producto, :guardar_producto]

    def listar
        @lista_pedidos = Pedido.select(:id, :codigo, :total, :created_at, :estados_pedido_id).order(created_at: :desc)
    end

    def mostrar
        
    end

    def crear
        @pedido = Pedido.new
        @pedido.codigo = SecureRandom.hex(4).upcase
        @pedido.total = 0
        @pedido.estados_pedido = EstadosPedido.find_by(estado: "Solicitado")
        @pedido.destino = Destino.find_by(nombre: 'Sin Destino')
        @pedido.datos_envio = DatosEnvio.create(
            nombre: 'Ingrese Nombre',
            telefono: 'Ingrese un teléfono',
            direccion: 'Ingrese dirección',
            correo: 'Ingrese un correo',
        )
        @pedido.save
        redirect_to admin_editar_pedido_path(@pedido)
        
    end

    def editar
        @datos_pedido = PedidosFormulario.new
        @datos_pedido.id = @pedido.id
        @datos_pedido.nombre = @pedido.datos_envio.nombre
        @datos_pedido.correo = @pedido.datos_envio.correo
        @datos_pedido.telefono = @pedido.datos_envio.telefono
        @datos_pedido.direccion = @pedido.datos_envio.direccion
        @datos_pedido.destino_id = @pedido.destino_id
        @datos_pedido.estado_id = @pedido.estados_pedido.id
        @destinos = Destino.select(:id, :nombre).order(nombre: :asc)
        @estados_pedidos = EstadosPedido.select(:id, :estado).order(id: :asc)
        @productos = @pedido.detalles_pedidos

    end


    def actualizar
        @datos_pedido = PedidosFormulario.new(params_pedidos)
        if @datos_pedido.valid?
            @pedido.datos_envio.nombre = @datos_pedido.nombre
            @pedido.datos_envio.correo = @datos_pedido.correo
            @pedido.datos_envio.telefono = @datos_pedido.telefono
            @pedido.datos_envio.direccion = @datos_pedido.direccion
            @pedido.destino = Destino.find(@datos_pedido.destino_id)
            @pedido.estados_pedido = EstadosPedido.find(@datos_pedido.estado_id)

            if @pedido.datos_envio.save and @pedido.save
                redirect_to action: :mostrar
            else
                @destinos = Destino.select(:id, :nombre).order(nombre: :asc)
                @estados_pedidos = EstadosPedido.select(:id, :estado).order(id: :asc)
                render :editar
            end
            
        else
            @destinos = Destino.select(:id, :nombre).order(nombre: :asc)
            @estados_pedidos = EstadosPedido.select(:id, :estado).order(id: :asc)
            render :editar
        end
    end

    def eliminar
        
    end

    def aumentar_cantidad_producto
        detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        detalle_pedido.cantidad += 1
        detalle_pedido.save

        redirect_to action: :editar
    end

    def disminuir_cantidad_producto
        detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        if detalle_pedido.cantidad - 1 <= 0
            detalle_pedido.destroy
        else
            detalle_pedido.cantidad -= 1
            detalle_pedido.save
        end

        redirect_to action: :editar
    end

    def eliminar_producto
        detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        detalle_pedido.destroy

        redirect_to action: :editar
    end

    def agregar_producto
        @todos_los_productos = Producto.select(:id, :nombre, :descripcion, :precio, :cantidad, :estados_producto_id).order(nombre: :asc).where("estados_producto_id = 1 and cantidad > 0")
    end

    def guardar_producto
        detalle_pedido = @pedido.detalles_pedidos.find_by(producto_id: params[:id_producto])
        if detalle_pedido
            detalle_pedido.cantidad += 1
        else
        detalle_pedido = DetallesPedido.new(
            pedido: @pedido,
            producto_id: params[:id_producto],
            cantidad: 1,
        )
        end
        detalle_pedido.save
        redirect_to action: :editar
    end

    private

    def params_pedidos
        params.require(:admin_pedidos_helper_pedidos_formulario).permit(:nombre, :correo, :telefono, :direccion, :destino_id, :estado_id)
    end

    def asignar_pedido
        @pedido = Pedido.find(params[:id])
    rescue ActiveRecord::RecordNotFound
        flash[:errors] = "Pedido no encontrado"
        redirect_to action: :listar
    end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController

    include PedidosHelper

    layout 'application', only: [:lista_pedidos, :detalles_pedidos]
    # en vez de hacer un layout especial para un controlador
    # podemos llamar a otro usando
    # layout 'paginas'

    before_action :validar_carro
    before_action :validar_productos_carro, only: :crear

    def crear
        @datos_formulario = DatosEnvioFormulario.new
        consultar_destinos
    end
    
    def pagar

    end

    def guardar
        @datos_formulario = DatosEnvioFormulario.new(params_datos_formulario)
        if @datos_formulario.valid? 
            @datos_envio = crear_datos_envio(@datos_formulario)
            @pedido = definir_pedido(
                @carro.total,
                @datos_formulario,
                @datos_envio
            )
            if @pedido.save
                migrar_productos(@carro, @pedido)
                enviar_confirmacion_pedido
                eliminar_carrito
                render :pagar
            else
                consultar_destinos
                render :crear
            end
        else
            # @datos_envio.valid?
            # @datos_envio.errors.add(:destino_id, "Seleccione un destino")
            consultar_destinos
            render :crear
        end
    end
    
    def lista_pedidos
        @lista_pedidos = Pedido.select(:created_at, :codigo, :total).order(created_at: :desc)
    end

    def detalles_pedidos
    end

    def eliminar_pedidos
        
    end
    

    private

    def params_datos_formulario
        params.require(:pedidos_helper_datos_envio_formulario).permit(:nombre, :direccion, :correo, :telefono, :destino_id)
    end

    def enviar_confirmacion_pedido
        ClienteMailer.with(datos_envio: @datos_envio, pedido_correo: @pedido).confirmacion_pedido.deliver_later
    end
    
    def eliminar_carrito
        session[:carro_id] = nil
        @carro.destroy
    end
    
    def consultar_destinos
        @destinos = Destino.select(:id, :nombre).order(nombre: :asc).select{ |d| d.nombre != "Sin Destino" }
    end

    def validar_productos_carro
        if @carro.productos.count.zero?
            redirect_to root_path
        end
    end

    # primera versión del controlador
    # def datos_envio_params
    #     params.require(:pedidos_helper_datos_envio_formulario).permit(:nombre, :direccion, :correo, :telefono)
    # end

    # def destino_params
    #     params.require(:pedidos_helper_datos_envio_formulario).permit(:destino_id)
    # end
    # def consultar_categorias
    #     @categorias = Categoria.select(:id, :categoria).order(categoria: :asc)
    # end
end

app/helpers/admin/pedidos_helper.rb
module Admin::PedidosHelper
    class PedidosFormulario
      
      include ActiveModel::Model
      attr_accessor(:id, :nombre, :correo, :direccion, :telefono, :destino_id, :estado_id)
      validates(:nombre, presence: true)
      validates(:direccion, presence: true)
      validates(:correo, presence: true)
      validates(:telefono, presence: true)
      validates(:destino_id, presence: true)
      

      def persisted?
        id != nil
      end

      
    end

    # def crear_datos_envio(pedido)
    #     DatosEnvio.create(
    #         nombre: datos_formulario.nombre,
    #         direccion: datos_formulario.direccion,
    #         telefono: datos_formulario.telefono,
    #         correo: datos_formulario.correo
    #     )
    # end

    # def definir_pedido(total, pedido, datos_envio)
    #     Pedido.new( 
    #         total: total, 
    #         destino_id: datos_formulario.destino_id,
    #         estados_pedido: EstadosPedido.find_by(estado: 'solicitando'), 
    #         datos_envio: datos_envio
    #     )
    # end

    # def migrar_productos(carro, pedido)
    #     carro.carros_contenidos.each do |contenido|
    #         DetallesPedido.create(
    #             pedido: pedido, 
    #             producto: contenido.producto, 
    #             cantidad: contenido.cantidad
    #         )
    #     end
    # end
  
end

app/helpers/pedidos_helper.rb
module PedidosHelper

    class DatosEnvioFormulario

        include ActiveModel::Model
        attr_accessor :nombre
        attr_accessor :correo
        attr_accessor :direccion
        attr_accessor :telefono
        attr_accessor :destino_id

        validates(:nombre, presence: true)
        validates(:direccion, presence: true)
        validates(:correo, presence: true)
        validates(:telefono, presence: true)
        validates(:destino_id, presence: true)

    end

    def crear_datos_envio(datos_formulario)
        DatosEnvio.create(
            nombre: datos_formulario.nombre,
            direccion: datos_formulario.direccion,
            telefono: datos_formulario.telefono,
            correo: datos_formulario.correo
        )
    end

    def definir_pedido(total, datos_formulario, datos_envio)
        Pedido.new(
            codigo: SecureRandom.hex(4).upcase, 
            total: total, 
            destino_id: datos_formulario.destino_id,
            estados_pedido: EstadosPedido.find_by(estado: 'Solicitado'), 
            datos_envio: datos_envio
        )
    end

    def migrar_productos(carro, pedido)
        carro.carros_contenidos.each do |contenido|
            DetallesPedido.create(
                pedido: pedido, 
                producto: contenido.producto, 
                cantidad: contenido.cantidad
            )
        end
    end

end

app/views/admin/pedidos/_edicion_productos_cliente.html.erb
<div class="row justify-content-between">
    <div class="col-4">
        <h1 class="my-3">Productos</h1>
    </div>
    <div class="col-2">
        <%= link_to admin_agregar_producto_path(@pedido), class: "btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Agregar Producto
        <% end %>
    </div>
</div>
<div class="card " >
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Carrito
        </li>
        <li class="list-group-item">
            <% productos.each do |detalle| %>
                <div class="row justify-content-between border-bottom ">
                    <div class="col-3  border-primary">
                        <% if detalle.producto.imagenes.attached? %>
                            <%= image_tag detalle.producto.imagenes.first, class: "w-50" %>
                        <% else %>
                            No hay imagenes registradas
                        <% end %>
                        
                    </div>
                    <div class="col-5 ">
                        <h4><%= detalle.producto.nombre %></h4>
                        <p><%= detalle.producto.descripcion %></p>
                        <p><b>Categoria: </b><%= detalle.producto.categoria.categoria %></p>
                    </div>
                    <div class="col-2">
                        <p class="d-inline">Cantidad: </p>
                        <%= link_to admin_disminuir_producto_path(detalle.pedido_id, detalle.producto_id), method: :delete, remote: true, class: "btn btn-secondary p-0 m-0 d-inline" do %>
                            <i class="bi bi-dash p-0 m-0"></i>
                        <% end %>
                        <p class = "d-inline ms-1"><%= detalle.cantidad %></p>
                        <%= link_to admin_aumentar_producto_path(detalle.pedido_id, detalle.producto_id), method: :put, remote: true, class: "btn btn-secondary p-0 m-0 d-inline" do %>
                            <i class="bi bi-plus "></i>
                        <% end %>
                        <%= link_to admin_eliminar_producto_path(detalle.pedido_id, detalle.producto_id), method: :delete, remote: true, data: { confirm: "¿Quieres eliminar el producto del Pedido?" }, class: "btn btn-danger px-1 py-0 ms-2" do %>                   
                            <i class="bi bi-trash-fill d-inline"></i>                    
                        <% end %>
                    </div>
                    <div class="col-2  text-end">
                        $<%= detalle.producto.precio * detalle.cantidad %> CLP
                    </div>
                </div>
            <% end %>
            <li class="list-group-item text-end">
            <strong>
                Subtotal: <%= pedido.total %>
            </strong>
        </li>
        </li>
    </ul>
    
</div>

app/views/admin/pedidos/_formulario_datos_cliente.html.erb
<div>
    <%= form_with(model: datos_pedido) do |formulario| %>
        
            <div class="mb-3 col-6 fw-bolder">
                <%= formulario.label :nombre, class: "form-label" %>
                <%= formulario.text_field :nombre, class: "form-control rounded-pill" %>
                <% if datos_pedido.errors[:nombre].any? %>
                    <p style="color:red;"> <%= datos_pedido.errors[:nombre].first %></p>
                <% end %>
            </div>
            <br>
            <div class="mb-3 col-6 fw-bolder">
                <%= formulario.label :correo, class: "form-label" %>
                <%= formulario.text_field :correo, class: "form-control rounded-pill" %>
                <% if datos_pedido.errors[:correo].any? %>
                    <p style="color:red;"> <%= datos_pedido.errors[:correo].first %></p>
                <% end %>
            </div>
            <br>
            <div class="mb-3 col-6 fw-bolder">
                <%= formulario.label :direccion, class: "form-label" %>
                <%= formulario.text_field :direccion, class: "form-control rounded-pill" %>
                <% if datos_pedido.errors[:direccion].any? %>
                    <p style="color:red;"> <%= datos_pedido.errors[:direccion].first %></p>
                <% end %>
            </div>
            <br>
            <div class="mb-3 col-6 fw-bolder">
                <%= formulario.label :telefono, class: "form-label" %>
                <%= formulario.text_field :telefono, class: "form-control rounded-pill" %>
                <% if datos_pedido.errors[:telefono].any? %>
                    <p style="color:red;"> <%= datos_pedido.errors[:telefono].first %></p>
                <% end %>
            </div>
            <br>
            <div class="mb-3 col-6 fw-bolder">
                <%= formulario.label :destino_id, class: "form-label" %>
                
                <%= formulario.select :destino_id, options_from_collection_for_select(destinos, :id, :nombre, datos_pedido.destino_id), {include_blank: "Elige una Ciudad..."}, { class: "form-select rounded-pill" } %>
                <% if datos_pedido.errors[:destino_id].any? %>
                    <p style="color:red;"> <%= datos_pedido.errors[:destino_id].first %></p>
                <% end %>
                
            </div>
            <br>
            <div class="mb-3 col-6 fw-bolder">
                <%= formulario.label :estado_id, class: "form-label" %>
                
                <%= formulario.select :estado_id, options_from_collection_for_select(estados_pedidos, :id, :estado, datos_pedido.estado_id), {}, { class: "form-select rounded-pill" } %>
                <% if datos_pedido.errors[:estado_id].any? %>
                    <p style="color:red;"> <%= datos_pedido.errors[:estado_id].first %></p>
                <% end %>
                
            </div>
            
            <%= formulario.submit  class: "btn btn-primary rounded-pill" %>

            
    <% end %>
</div>

app/views/admin/pedidos/agregar_producto.html.erb
<div class="row justify-content-between mb-4">
    <div class="col-9">
        <h1>Agregar Productos al Pedido: <%= @pedido.codigo %></h1>
    </div>
    <div class="col-3">
        <%= link_to admin_editar_pedido_path(@pedido), class: "btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Volver a Editar Pedido
        <% end %>
    </div>
</div>
<h1>Productos</h1>
<div class="row">
    <% @todos_los_productos.each do |producto| %>
        <div class="col-lg-3 col-sm-10">
            <div class="card my-3 border border-primary border-2 shadow rounded tarjeta-productos">
                <div class="seccion-imagen-tarjetas border-bottom"> 
                    <% if producto.imagenes.attached? %>
                        <%= image_tag producto.imagenes.first, class: "imagen-tarjetas card-img-top ", alt: "..." %>
                    <% else %>
                        No hay imagenes registradas
                    <% end %>
                    
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= producto.nombre %></h5>
                    <p class="card-text descripcion"><%= producto.descripcion %></p>
                    <h5 class="card-title precio">Precio: $<%= producto.precio.to_s[0..-3] %></h5>
                    <%= link_to "Agregar al Pedido", admin_guardar_producto_path(@pedido, producto), class: "agregar-al-carro btn btn-primary", method: :post, remote: true %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/pedidos/editar.html.erb
<div class="row justify-content-between mb-4">
    <div class="col-5">
        <h1>Editar Pedido: <%= @pedido.codigo %></h1>
    </div>
    <div class="col-3">
        <%= link_to admin_pedido_path, class: "btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Volver al Pedido
        <% end %>
    </div>
</div>
<%= render "formulario_datos_cliente", datos_pedido: @datos_pedido, destinos: @destinos, estados_pedidos: @estados_pedidos %>
<br>
<%= render "edicion_productos_cliente", productos: @productos, pedido: @pedido %>

app/views/admin/pedidos/listar.html.erb
<div class="row my-4 justify-content-between">
        <% if flash[:errors] %>
            <div class="alert alert-warning" role="alert">
            <%= flash[:errors] %>
            </div>
        <% end %>
        <div class="col-4">
            <h1 class="titulo-seccion">Lista de Pedidos</h1>
        </div>
        
        <div class="col-4">
            <%= link_to admin_pedidos_helper_pedidos_formularios_path, method: :post, data: {confirm: '¿Seguro quieres crear un nuevo pedido?'}, class: "btn btn-primary boton-izquierda" do %>
                <i class="bi bi-plus-circle"></i>
                Crear Nuevo Pedido
            <% end %>
            <%= link_to admin_productos_path, class: "btn btn-primary boton-derecha" do %>
                <i class="bi bi-card-list"></i>
                Lista Productos
            <% end %>
        </div>
    </div>
    <div class="row my-2 justify-content-between">
        <div class="col-2 ms-2">
            <h3>Código</h3>
        </div>
        <div class="col-2 ms-2">
            <h3>Estado</h3>
        </div>
        <div class="col-2 ">
            <h3>Total</h3>
        </div>
        <div class="col-2">
            <h3>Fecha</h3>
        </div>
        <div class="col-1 me-5">
            <h3>Acciones</h3>
        </div>
    </div>
    <% @lista_pedidos.each do |pedido| %>
        <div class="row my-3 mx-0 p-0 justify-content-between border border-1 border-primary rounded-pill shadow rounded hover filas-lista-pedidos">
            <div class="col-2 ms-2 my-auto fw-bold fs-5"><%= pedido.codigo %></div>
            <div class="col-2 ms-5 my-auto fw-normal fs-5"><%= pedido.estados_pedido.estado %></div>
            <div class="col-2 ms-5 my-auto fw-normal fs-5"><%= pedido.total %></div>
            <div class="col-2 ms-5 my-auto fw-normal fs-5"><%= pedido.created_at.strftime("%d/%m/%Y") %></div>
            <div class="col-2  p-0 ms-1 my-1">
                <%= link_to admin_pedido_path(pedido), class: "btn btn-primary rounded-pill ms-5" do %>
                    <i class="bi bi-search"></i>
                    Ver Detalles
                <% end %>
                
            </div>
        </div>
    <% end %>

app/views/admin/pedidos/mostrar.html.erb
<div class="row justify-content-between">    
    <div class="col-4 alert alert-primary rounded-pill" role="alert">
        <h3>
            Estado Pedido: <%= @pedido.estados_pedido.estado %>
        </h3>
    </div>
    <div class="col-2">
        <%= link_to admin_pedidos_path, class: "btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Lista Pedidos
        <% end %>
    </div>
</div>
<div class="border border-3 ">   
    <div class="row justify-content-between">
        <div class="col-1 ms-3 ">
            <h4>Código</h4>
        </div>
        <div class="col-3 ms-4">
            <h4>Datos Cliente</h4>
        </div>
        <div class="col-4 ms-4">
            <h4>Detalle Compra</h4>
        </div>
        <div class="col-1 ">
            <h4>Total</h4>
        </div>
        <div class="col-2 ms-4">
            <h4>Acciones</h4>
        </div>
    </div>
    <div class="row my-2 justify-content-between">
        <div class="col-1 ms-3 ">
            <h5><%= @pedido.codigo %></h5>
        </div>
        <div class="col-3 ms-4">
            <p><%= @pedido.datos_envio.nombre %></p>
            <p><%= @pedido.datos_envio.correo %></p>
            <p><%= @pedido.datos_envio.telefono %></p>
            <p><%= @pedido.datos_envio.direccion %></p>
        </div>
        <div class="col-4 ms-4">
            <% @pedido.detalles_pedidos.each do |detalle| %>
                <p>Producto: <%= detalle.producto.nombre %></p>
                <p>Precio Unitario: <%= detalle.producto.precio %></p>
                <p>Cantidad: <%= detalle.cantidad %></p>
            <% end %>
        </div>
        <div class="col-1">
            <h5>$<%= @pedido.total %></h5>
        </div>
        <div class="col-2 ms-4">
            <%= link_to admin_editar_pedido_path(@pedido), class: "btn btn-warning rounded-pill" do %>
                    <i class="bi bi-pencil-fill"></i>
                    Editar
                <% end %>
        </div>
    </div>              
    
</div>            