config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    unlocks: 'usuarios/unlocks',
    passwords: 'usuarios/passwords',
    confirmations: 'usuarios/confirmations',
    omniauthable: 'usuarios/omniauths_callbacks'
  }
  #Rutas para inicio de sesión de administradores
  #Como el inicio lo haremos en un boton dentro de la barra de navegación, no haremos un get sino solamente un post y delete
  #get "/",                to: "sesiones#login", as: "login"
  post "sesiones",        to: "sesiones#iniciar_sesion",     as: "iniciar_sesion"
  delete "sesiones",      to: "sesiones#cerrar_sesion",      as: "cerrar_sesion"
  
  root 'paginas#inicio'
  get 'carrito',          to: 'paginas#carro',          as: 'carrito'

  

  #carros
  post 'carros/:producto_id',             to: 'carros#agregar_producto',        as: 'agregar_producto'
  put 'carros/:producto_id/cantidad',    to: 'carros#aumentar_un_producto',    as: 'aumentar_producto'
  delete 'carros/:id_producto',           to: 'carros#eliminar_producto',       as:'eliminar_producto'
  delete 'carros/:id_producto/cantidad',  to: 'carros#disminuir_un_producto',   as:'disminuir_producto'
  
  
  
  #delete 'productos/:id',      to: 'productos#eliminar'  no lo utilizamos por la razon explicada en el controlador.


  #delete especial para borrar sólo una foto
  

  


  get 'pedidos',                    to: 'pedidos#crear',            as: 'nuevo_pedido'
  get 'pagar',                      to: 'pedidos#pagar',            as: 'pagar'
  get 'pedidos/lista_pedidos',      to: 'pedidos#lista_pedidos',    as: 'lista_pedidos'
  get 'pedidos/detalles_pedidos',   to: 'pedidos#detalles_pedidos', as: 'detalles_pedidos' 

  post 'pedidos',             to: 'pedidos#guardar',    as: 'crear_pedido_cliente'

  namespace :admin do
    get "categorias",                                     to: "categorias#index",       as: "categorias"
    get "categorias/crear",                               to: "categorias#crear",       as: "nueva_categoria"
    get "categorias/:id",                                 to: "categorias#mostrar",     as: "categoria"
    get "categorias/:id/editar",                          to: "categorias#editar",      as: "editar_categorias"

    post "categorias/guardar",                            to: "categorias#guardar"
    put "categorias/:id",                                 to: "categorias#actualizar"
    patch "categorias/:id",                               to: "categorias#actualizar"
    delete "categorias/:id",                              to: "categorias#eliminar"

    get "productos",                                      to: "productos#index",        as: "productos"
    get "productos/crear",                                to: "productos#crear",        as: "nuevo_producto"
    get "productos/:id",                                  to: "productos#mostrar",      as: "producto"
    get "productos/:id/editar",                           to: "productos#editar",       as: "editar_productos"

    post "productos/guardar",                             to: "productos#guardar"
    put "productos/:id",                                  to: "productos#actualizar"
    patch "productos/:id",                                to: "productos#actualizar"
    delete "productos/:id/imagenes/:id_imagen",           to: "productos#eliminar_foto", as: "eliminar_foto"

    get "destinos",                                       to: "destinos#listar",        as: "destinos"
    get "destinos/crear",                                 to: "destinos#crear",         as: "nuevo_destino"
    get "destinos/:id",                                   to: "destinos#mostrar",       as: "destino"
    get "destinos/:id/editar",                            to: "destinos#editar",        as: "editar_destinos"

    post "destinos/guardar",                              to: "destinos#guardar"
    put "destinos/:id",                                   to: "destinos#actualizar"
    patch "destinos/:id",                                 to: "destinos#actualizar"
    delete "destinos/:id",                                to: "destinos#eliminar"

    get "/",                                              to: "pedidos#listar",         as: "pedidos"
    #get "pedidos",                                        to: "pedidos#crear",          as: "nuevo_pedido"
    get "pedidos/:id",                                    to: "pedidos#mostrar",        as: "pedido"
    get "pedidos/:id/editar",                             to: "pedidos#editar",         as: "editar_pedido"
    get "pagar",                                          to: "pedidos#pagar",          as: "pagar"

    post "pedidos",                                       to: "pedidos#crear",        as: "pedidos_helper_pedidos_formularios"
    put "pedidos/:id",                                    to: "pedidos#actualizar"     
    patch "pedidos/:id",                                  to: "pedidos#actualizar",     as: "pedidos_helper_pedidos_formulario"
    delete "pedidos/:id",                                 to: "pedidos#eliminar"

    # rutas para crear un producto ded un pedido
    get "pedidos/:id/productos",                              to: "pedidos#agregar_producto",             as: "agregar_producto"
    post "pedidos/:id/productos/:id_producto",                to: "pedidos#guardar_producto",             as: "guardar_producto"
    put "pedidos/:id/productos/:id_producto",                 to: "pedidos#aumentar_cantidad_producto",   as: "aumentar_producto"
    delete "pedidos/:id/productos/:id_producto",              to: "pedidos#disminuir_cantidad_producto",  as: "disminuir_producto"
    delete "pedidos/:id/productos/:id_producto/eliminar",     to: "pedidos#eliminar_producto",            as: "eliminar_producto"

    
        
  end

end

app/controllers/paginas_controller.rb
class PaginasController < ApplicationController
    
    before_action :validar_carro
    

    def inicio
        @todos_los_productos = Producto.select(:id, :nombre, :descripcion, :precio, :cantidad, :estados_producto_id).order(nombre: :asc).where("estados_producto_id = 1 and cantidad > 0")
    end
    
    def Carro
        
    end
    
    private

        

end

app/helpers/paginas_helper.rb
module PaginasHelper
end

app/views/paginas/carro.html.erb
<div class="card " >
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            Carrito
        </li>
        <li class="list-group-item">
            <% @carro.carros_contenidos.each do |contenido_carrito| %>
                <div class="row justify-content-between border-bottom ">
                    <div class="col-3  border-primary">
                        <% if contenido_carrito.producto.imagenes.attached? %>
                            <%= image_tag contenido_carrito.producto.imagenes.first, class: "w-50" %>
                        <% else %>
                            No hay imagenes registradas
                        <% end %>
                        
                    </div>
                    <div class="col-5 ">
                        <h4><%= contenido_carrito.producto.nombre %></h4>
                        <p><%= contenido_carrito.producto.descripcion %></p>
                        <p><b>Categoria: </b><%= contenido_carrito.producto.categoria.categoria %></p>
                    </div>
                    <div class="col-2">
                        <p class="d-inline">Cantidad: </p>
                        <%= link_to disminuir_producto_path(contenido_carrito.producto), method: :delete, remote: true, class: 'btn btn-secondary p-0 m-0 d-inline' do%>
                            <i class="bi bi-dash p-0 m-0"></i>
                        <% end %>
                        <p class = "d-inline ms-1"><%= contenido_carrito.cantidad %></p>
                        <%= link_to aumentar_producto_path(contenido_carrito.producto), method: :put, remote: true, class:'btn btn-secondary p-0 m-0 d-inline' do%>
                            <i class="bi bi-plus "></i>
                        <% end %>
                        <%= link_to eliminar_producto_path(contenido_carrito.producto), method: :delete, data: { confirm: '¿Quieres eliminar el producto de tu carrito?' }, class:"btn btn-danger px-1 py-0 ms-2" do %>                   
                            <i class="bi bi-trash-fill d-inline"></i>                    
                        <% end %>
                    </div>
                    <div class="col-2  text-end">
                        $<%= contenido_carrito.producto.precio %> CLP
                    </div>
                </div>
            <% end %>
        </li>
        <li class="list-group-item text-end">
            <strong>
                Subtotal: <%= @carro.total %>
            </strong>
        </li>
    </ul>
    <div class="row">
        <%= link_to "Continuar con el Pedido", nuevo_pedido_path , class:"btn btn-primary"  %>
    </div>
</div>

app/views/paginas/inicio.html.erb
<h1>Productos</h1>
<div class="container row">
    <% @todos_los_productos.each do |producto| %>
        <div class="col-lg-3 col-sm-10">
            <div class="card my-3 border border-primary border-2 shadow rounded tarjeta-productos">
                <div class="seccion-imagen-tarjetas border-bottom"> 
                    <% if producto.imagenes.attached? %>
                        <%= image_tag producto.imagenes.first, class: "imagen-tarjetas card-img-top ", alt:"..." %>
                    <% else %>
                        No hay imagenes registradas
                    <% end %>
                    
                </div>
                <div class="card-body">
                    <h5 class="card-title"><%= producto.nombre %></h5>
                    <p class="card-text descripcion"><%= producto.descripcion %></p>
                    <h5 class="card-title precio">Precio: $<%= producto.precio %></h5>
                    <%= link_to 'Agregar al carro', agregar_producto_path(producto), class: 'agregar-al-carro btn btn-primary', method: :post, remote: true %>
                </div>
            </div>
        </div>
    <% end %>
</div>