config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    unlocks: 'usuarios/unlocks',
    passwords: 'usuarios/passwords',
    confirmations: 'usuarios/confirmations',
    omniauthable: 'usuarios/omniauths_callbacks'
  }
  #Rutas para inicio de sesión de administradores
  #Como el inicio lo haremos en un boton dentro de la barra de navegación, no haremos un get sino solamente un post y delete
  #get "/",                to: "sesiones#login", as: "login"
  post "sesiones",        to: "sesiones#iniciar_sesion",     as: "iniciar_sesion"
  delete "sesiones",      to: "sesiones#cerrar_sesion",      as: "cerrar_sesion"
  
  root 'paginas#inicio'
  get 'carrito',          to: 'paginas#carro',          as: 'carrito'

  

  #carros
  post 'carros/:producto_id',             to: 'carros#agregar_producto',        as: 'agregar_producto'
  put 'carros/:producto_id/cantidad',    to: 'carros#aumentar_un_producto',    as: 'aumentar_producto'
  delete 'carros/:id_producto',           to: 'carros#eliminar_producto',       as:'eliminar_producto'
  delete 'carros/:id_producto/cantidad',  to: 'carros#disminuir_un_producto',   as:'disminuir_producto'
  
  
  
  #delete 'productos/:id',      to: 'productos#eliminar'  no lo utilizamos por la razon explicada en el controlador.


  #delete especial para borrar sólo una foto
  

  


  get 'pedidos',                    to: 'pedidos#crear',            as: 'nuevo_pedido'
  get 'pagar',                      to: 'pedidos#pagar',            as: 'pagar'
  get 'pedidos/lista_pedidos',      to: 'pedidos#lista_pedidos',    as: 'lista_pedidos'
  get 'pedidos/detalles_pedidos',   to: 'pedidos#detalles_pedidos', as: 'detalles_pedidos' 

  post 'pedidos',             to: 'pedidos#guardar',    as: 'crear_pedido_cliente'

  namespace :admin do
    get "categorias",                                     to: "categorias#index",       as: "categorias"
    get "categorias/crear",                               to: "categorias#crear",       as: "nueva_categoria"
    get "categorias/:id",                                 to: "categorias#mostrar",     as: "categoria"
    get "categorias/:id/editar",                          to: "categorias#editar",      as: "editar_categorias"

    post "categorias/guardar",                            to: "categorias#guardar"
    put "categorias/:id",                                 to: "categorias#actualizar"
    patch "categorias/:id",                               to: "categorias#actualizar"
    delete "categorias/:id",                              to: "categorias#eliminar"

    get "productos",                                      to: "productos#index",        as: "productos"
    get "productos/crear",                                to: "productos#crear",        as: "nuevo_producto"
    get "productos/:id",                                  to: "productos#mostrar",      as: "producto"
    get "productos/:id/editar",                           to: "productos#editar",       as: "editar_productos"

    post "productos/guardar",                             to: "productos#guardar"
    put "productos/:id",                                  to: "productos#actualizar"
    patch "productos/:id",                                to: "productos#actualizar"
    delete "productos/:id/imagenes/:id_imagen",           to: "productos#eliminar_foto", as: "eliminar_foto"

    get "destinos",                                       to: "destinos#listar",        as: "destinos"
    get "destinos/crear",                                 to: "destinos#crear",         as: "nuevo_destino"
    get "destinos/:id",                                   to: "destinos#mostrar",       as: "destino"
    get "destinos/:id/editar",                            to: "destinos#editar",        as: "editar_destinos"

    post "destinos/guardar",                              to: "destinos#guardar"
    put "destinos/:id",                                   to: "destinos#actualizar"
    patch "destinos/:id",                                 to: "destinos#actualizar"
    delete "destinos/:id",                                to: "destinos#eliminar"

    get "/",                                              to: "pedidos#listar",         as: "pedidos"
    #get "pedidos",                                        to: "pedidos#crear",          as: "nuevo_pedido"
    get "pedidos/:id",                                    to: "pedidos#mostrar",        as: "pedido"
    get "pedidos/:id/editar",                             to: "pedidos#editar",         as: "editar_pedido"
    get "pagar",                                          to: "pedidos#pagar",          as: "pagar"

    post "pedidos",                                       to: "pedidos#crear",        as: "pedidos_helper_pedidos_formularios"
    put "pedidos/:id",                                    to: "pedidos#actualizar"     
    patch "pedidos/:id",                                  to: "pedidos#actualizar",     as: "pedidos_helper_pedidos_formulario"
    delete "pedidos/:id",                                 to: "pedidos#eliminar"

    # rutas para crear un producto ded un pedido
    get "pedidos/:id/productos",                              to: "pedidos#agregar_producto",             as: "agregar_producto"
    post "pedidos/:id/productos/:id_producto",                to: "pedidos#guardar_producto",             as: "guardar_producto"
    put "pedidos/:id/productos/:id_producto",                 to: "pedidos#aumentar_cantidad_producto",   as: "aumentar_producto"
    delete "pedidos/:id/productos/:id_producto",              to: "pedidos#disminuir_cantidad_producto",  as: "disminuir_producto"
    delete "pedidos/:id/productos/:id_producto/eliminar",     to: "pedidos#eliminar_producto",            as: "eliminar_producto"

    
        
  end

end

app/models/destino.rb
class Destino < ApplicationRecord
  belongs_to :region
  has_many :pedidos

  validates(:nombre, presence: true)
  validates(:region_id, presence: true)
end

app/controllers/admin/destinos_controller.rb
class Admin::DestinosController < Admin::AdminController
    
    before_action :asignar_destino, only: [:mostrar, :editar, :actualizar, :eliminar]

    def listar
        @destinos = Destino.select(:id, :nombre).where("nombre <> 'Sin Destino'")
    end

    def crear
        @destino = Destino.new
        consultar_regiones
    end

    def guardar
        @destino = Destino.new(destino_params)
        if @destino.save
            redirect_to action: :listar
        else
            consultar_regiones
            render :crear
        end
    end

    def mostrar

    end

    def editar
        consultar_regiones
        
    end

    def actualizar
        if @destino.update(destino_params)
            redirect_to action: :listar
        else
            consultar_regiones
            render :editar
        end
    end

    def eliminar
        @destino.destroy
        redirect_to action: :listar
    end

    private

    def destino_params
        params.require(:destino).permit(:nombre, :region_id)
    end

    def asignar_destino
        @destino = Destino.find(params[:id])
    end

    def consultar_regiones
        @regiones = Region.select(:id, :nombre).order(id: :asc)
    end

end

app/controllers/destinos_controller.rb
class DestinosController < ApplicationController
    
    before_action :asignar_destino, only: [:mostrar, :editar, :actualizar, :eliminar]

    def listar
        @destinos = Destino.select(:id, :nombre)
    end

    def crear
        @destino = Destino.new
        consultar_regiones
    end

    def guardar
        @destino = Destino.new(destino_params)
        if @destino.save
            redirect_to action: :listar
        else
            consultar_regiones
            render :crear
        end
    end

    def mostrar

    end

    def editar
        consultar_regiones
        
    end

    def actualizar
        if @destino.update(destino_params)
            redirect_to action: :listar
        else
            consultar_regiones
            render :editar
        end
    end

    def eliminar
        @destino.destroy
        redirect_to destinos_path
    end

    private

    def destino_params
        params.require(:destino).permit(:nombre, :region_id)
    end

    def asignar_destino
        @destino = Destino.find(params[:id])
    end

    def consultar_regiones
        @regiones = Region.select(:id, :nombre).order(id: :asc)
    end

end

app/helpers/destinos_helper.rb
module DestinosHelper
end

app/views/admin/destinos/crear.html.erb
<div class="row justify-content-between mb-4">
    <div class="col-4">    
        <h1>Crear Nuevo Destino</h1>
    </div>
    <div class="col-3 ms-5">
        <%= link_to admin_destinos_path, class:"btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Volver a Lista Destinos
        <% end %>
    </div>
</div>
<div class="fw-bolder" >    
    <%= form_with(model: [:admin, @destino], url: '/admin/destinos/guardar') do |formulario| %>
        
            <div class="mb-3 col-6">
                <%= formulario.label :nombre, class: 'form-label' %>
                <%= formulario.text_field :nombre, class: 'form-control rounded-pill', autofocus: "autofocus" %>
                <% if @destino.errors[:nombre].any? %>
                    <p style="color:red;"> <%= @destino.errors[:nombre].first %></p>
                <% end %>
            </div>
            
            <div class="mb-3 col-6 fw-bolder">
                <%= formulario.label :region_id, class: 'form-label' %>
                
                <%= formulario.select :region_id, options_from_collection_for_select(@regiones, :id, :nombre), {include_blank: "Elige una categoría..."}, {class: 'form-select rounded-pill'} %>
                
                <% if @destino.errors[:region_id].any? %>
                    <p style="color:red;"> <%= @destino.errors[:region_id].first %></p>
                <% end %>
            </div>
            
            <%= formulario.submit 'Crear Destino', class:"btn btn-primary rounded-pill" %>
</div>
<% end %>

app/views/admin/destinos/editar.html.erb
<div class="row justify-content-between mb-4">
    <div class="col-4">    
        <h1>Editar Destino</h1>
    </div>
    <div class="col-3 ms-5">
        <%= link_to admin_destinos_path, class:"btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Volver a Lista Destinos
        <% end %>
    </div>
</div>
<div class="fw-bolder">
    <%= form_with(model: [:admin, @destino]) do |formulario| %>
        <div class="mb-3 col-6">
            <%= formulario.label :nombre, class:"form-label" %>
            
            <%= formulario.text_field :nombre, class:"form-control rounded-pill", autofocus: "autofocus" %>
            <% if @destino.errors[:nombre].any? %>
                <%= @destino.errors[:nombre].first %>
            <% end %>
            
            
        </div>
        <div class="mb-3 col-6 fw-bolder">
            <%= formulario.label :region_id, class: 'form-label' %>
            
            <%= formulario.select :region_id, options_from_collection_for_select(@regiones, :id, :nombre), {include_blank: "Elige una categoría..."}, {class: 'form-select rounded-pill'} %>
            
            <% if @destino.errors[:region_id].any? %>
                <p style="color:red;"> <%= @destino.errors[:region_id].first %></p>
            <% end %>
        </div>
        <%= formulario.submit 'Editar', class:"btn btn-primary rounded-pill" %>
    <% end %>
</div>

app/views/admin/destinos/listar.html.erb
<div class="row my-4 justify-content-between">
        
        <div class="col-4">
            <h1 class="titulo-seccion">Lista de Destinos</h1>
        </div>
        
        <div class="col-4">
            <%= link_to admin_nuevo_destino_path, class:"btn btn-primary boton-izquierda" do %>
                <i class="bi bi-plus-circle"></i>
                Crear Nuevo Destino
            <% end %>
            <%= link_to admin_productos_path, class:"btn btn-primary boton-derecha" do %>
                <i class="bi bi-card-list"></i>
                Lista Productos
            <% end %>
        </div>
    </div>
    <div class="row my-2 justify-content-between">
        <div class="col-4">
            <h3>Nombre</h3>
        </div>
        <div class="col-2 me-4">
            <h3>Acciones</h3>
        </div>
    </div>
    <% @destinos.each do |destino| %>
        <div class="row my-3 justify-content-between border border-2 border-primary rounded-pill shadow rounded hover filas-lista-categorias">
            <div class="col-4 ms-3 my-auto fw-bolder fs-5"><%= destino.nombre %></div>
            <div class="col-2  p-0 mx-0 my-1">
                <%= link_to admin_editar_destinos_path(destino), class:"btn btn-warning boton-izquierda" do %>
                    <i class="bi bi-pencil-fill"></i>
                    Editar
                <% end %>
                <%= link_to admin_destino_path(destino), method: :delete, data: { confirm: '¿Quieres eliminar la categoria?' }, class:"btn btn-danger boton-derecha" do %>                   
                    <i class="bi bi-trash-fill"></i>
                    Eliminar                    
                <% end %>
            </div>
        </div>
    <% end %>