config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations',
    unlocks: 'usuarios/unlocks',
    passwords: 'usuarios/passwords',
    confirmations: 'usuarios/confirmations',
    omniauthable: 'usuarios/omniauths_callbacks'
  }
  #Rutas para inicio de sesión de administradores
  #Como el inicio lo haremos en un boton dentro de la barra de navegación, no haremos un get sino solamente un post y delete
  #get "/",                to: "sesiones#login", as: "login"
  post "sesiones",        to: "sesiones#iniciar_sesion",     as: "iniciar_sesion"
  delete "sesiones",      to: "sesiones#cerrar_sesion",      as: "cerrar_sesion"
  
  root 'paginas#inicio'
  get 'carrito',          to: 'paginas#carro',          as: 'carrito'

  

  #carros
  post 'carros/:producto_id',             to: 'carros#agregar_producto',        as: 'agregar_producto'
  put 'carros/:producto_id/cantidad',    to: 'carros#aumentar_un_producto',    as: 'aumentar_producto'
  delete 'carros/:id_producto',           to: 'carros#eliminar_producto',       as:'eliminar_producto'
  delete 'carros/:id_producto/cantidad',  to: 'carros#disminuir_un_producto',   as:'disminuir_producto'
  
  
  
  #delete 'productos/:id',      to: 'productos#eliminar'  no lo utilizamos por la razon explicada en el controlador.


  #delete especial para borrar sólo una foto
  

  


  get 'pedidos',                    to: 'pedidos#crear',            as: 'nuevo_pedido'
  get 'pagar',                      to: 'pedidos#pagar',            as: 'pagar'
  get 'pedidos/lista_pedidos',      to: 'pedidos#lista_pedidos',    as: 'lista_pedidos'
  get 'pedidos/detalles_pedidos',   to: 'pedidos#detalles_pedidos', as: 'detalles_pedidos' 

  post 'pedidos',             to: 'pedidos#guardar',    as: 'crear_pedido_cliente'

  namespace :admin do
    get "categorias",                                     to: "categorias#index",       as: "categorias"
    get "categorias/crear",                               to: "categorias#crear",       as: "nueva_categoria"
    get "categorias/:id",                                 to: "categorias#mostrar",     as: "categoria"
    get "categorias/:id/editar",                          to: "categorias#editar",      as: "editar_categorias"

    post "categorias/guardar",                            to: "categorias#guardar"
    put "categorias/:id",                                 to: "categorias#actualizar"
    patch "categorias/:id",                               to: "categorias#actualizar"
    delete "categorias/:id",                              to: "categorias#eliminar"

    get "productos",                                      to: "productos#index",        as: "productos"
    get "productos/crear",                                to: "productos#crear",        as: "nuevo_producto"
    get "productos/:id",                                  to: "productos#mostrar",      as: "producto"
    get "productos/:id/editar",                           to: "productos#editar",       as: "editar_productos"

    post "productos/guardar",                             to: "productos#guardar"
    put "productos/:id",                                  to: "productos#actualizar"
    patch "productos/:id",                                to: "productos#actualizar"
    delete "productos/:id/imagenes/:id_imagen",           to: "productos#eliminar_foto", as: "eliminar_foto"

    get "destinos",                                       to: "destinos#listar",        as: "destinos"
    get "destinos/crear",                                 to: "destinos#crear",         as: "nuevo_destino"
    get "destinos/:id",                                   to: "destinos#mostrar",       as: "destino"
    get "destinos/:id/editar",                            to: "destinos#editar",        as: "editar_destinos"

    post "destinos/guardar",                              to: "destinos#guardar"
    put "destinos/:id",                                   to: "destinos#actualizar"
    patch "destinos/:id",                                 to: "destinos#actualizar"
    delete "destinos/:id",                                to: "destinos#eliminar"

    get "/",                                              to: "pedidos#listar",         as: "pedidos"
    #get "pedidos",                                        to: "pedidos#crear",          as: "nuevo_pedido"
    get "pedidos/:id",                                    to: "pedidos#mostrar",        as: "pedido"
    get "pedidos/:id/editar",                             to: "pedidos#editar",         as: "editar_pedido"
    get "pagar",                                          to: "pedidos#pagar",          as: "pagar"

    post "pedidos",                                       to: "pedidos#crear",        as: "pedidos_helper_pedidos_formularios"
    put "pedidos/:id",                                    to: "pedidos#actualizar"     
    patch "pedidos/:id",                                  to: "pedidos#actualizar",     as: "pedidos_helper_pedidos_formulario"
    delete "pedidos/:id",                                 to: "pedidos#eliminar"

    # rutas para crear un producto ded un pedido
    get "pedidos/:id/productos",                              to: "pedidos#agregar_producto",             as: "agregar_producto"
    post "pedidos/:id/productos/:id_producto",                to: "pedidos#guardar_producto",             as: "guardar_producto"
    put "pedidos/:id/productos/:id_producto",                 to: "pedidos#aumentar_cantidad_producto",   as: "aumentar_producto"
    delete "pedidos/:id/productos/:id_producto",              to: "pedidos#disminuir_cantidad_producto",  as: "disminuir_producto"
    delete "pedidos/:id/productos/:id_producto/eliminar",     to: "pedidos#eliminar_producto",            as: "eliminar_producto"

    
        
  end

end

app/models/categoria.rb
class Categoria < ApplicationRecord
    has_many :productos
    validates(:categoria, uniqueness: true)
    validates(:categoria, presence: true)
end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::AdminController

    before_action :asignar_categoria, only: [:mostrar, :editar, :actualizar, :eliminar]

    def index
        @lista_categorias = Categoria.select(:id, :categoria).order(id: :asc)
    end

    def crear
        @categoria_nueva = Categoria.new
    end

    def guardar
        @categoria_nueva = Categoria.new(categoria_params)

        if @categoria_nueva.save
            redirect_to action: :index
        else
            render :crear
        end
    end

    def mostrar

    end

    def editar

    end

    def actualizar
        if @categoria_nueva.update(categoria_params)
            redirect_to action: :index
        else
            render :editar
        end
    end

    def eliminar
        @categoria_nueva.destroy
        redirect_to action: :index
    end

    

    private

    def categoria_params
        params.require(:categoria).permit(:categoria)
    end

    def asignar_categoria
        @categoria_nueva = Categoria.find(params[:id])
    end

end

app/controllers/categorias_controller.rb
class CategoriasController < ApplicationController

    before_action :asignar_categoria, only: [:mostrar, :editar, :actualizar, :eliminar]

    def index
        @lista_categorias = Categoria.select(:id, :categoria).order(id: :asc)
    end

    def crear
        @categoria_nueva = Categoria.new
    end

    def guardar
        @categoria_nueva = Categoria.new(categoria_params)

        if @categoria_nueva.save
            redirect_to action: :index
        else
            render :crear
        end
    end

    def mostrar

    end

    def editar

    end

    def actualizar
        if @categoria_nueva.update(categoria_params)
            redirect_to action: :index
        else
            render :editar
        end
    end

    def eliminar
        @categoria_nueva.destroy
        redirect_to categorias_path
    end

    

    private

    def categoria_params
        params.require(:categoria).permit(:categoria)
    end

    def asignar_categoria
        @categoria_nueva = Categoria.find(params[:id])
    end

end

app/helpers/categorias_helper.rb
module CategoriasHelper
end

app/views/admin/categorias/_formulario.html.erb
<div class="mb-3 col-6">
    <%= form_with(model: [:admin, categoria]) do |formulario| %>
        <%= formulario.label :categoria, class:"form-label" %>
         
        <%= formulario.text_field :categoria, class:"form-control rounded-pill", autofocus: "autofocus" %>
        <% if categoria.errors[:categoria].any? %>
            <%= categoria.errors[:categoria].first %>
        <% end %>
        <br>
        <%= formulario.submit 'Editar', class:"btn btn-primary rounded-pill" %>
    <% end %>
</div>

app/views/admin/categorias/crear.html.erb
<div class="row justify-content-between mb-4">
    <div class="col-4">    
        <h1>Crear Nueva Categoría</h1>
    </div>
    <div class="col-3 ms-5">
        <%= link_to admin_categorias_path, class:"btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Volver a Lista Categorías
        <% end %>
    </div>
</div>
<div class="fw-bolder" >    
    <%= form_with(model: @categoria_nueva, url: '/admin/categorias/guardar') do |formulario| %>
        <% if @categoria_nueva.errors.any? %>
            <% @categoria_nueva.errors.each do |error| %>
                <p style="color:red;"> <%= error.full_message %></p>
            <% end %>
        <% end %>
            <div class="mb-3 col-6">
                <%= formulario.label :categoria, class: 'form-label' %>
                <%= formulario.text_field :categoria, class: 'form-control rounded-pill', autofocus: "autofocus" %>
            </div>
            <br>
            
            <%= formulario.submit 'Crear Categoria', class:"btn btn-primary rounded-pill" %>
</div>
<% end %>

app/views/admin/categorias/editar.html.erb
<div class="row justify-content-between mb-4">
    <div class="col-4">    
        <h1>Editar Categoría</h1>
    </div>
    <div class="col-3 ms-5">
        <%= link_to admin_categorias_path, class:"btn btn-primary rounded-pill" do %>
            <i class="bi bi-card-list"></i>
            Volver a Lista Categorías
        <% end %>
    </div>
</div>
<div class="fw-bolder">
    <%= render 'formulario', categoria: @categoria_nueva %>
</div>

app/views/admin/categorias/index.html.erb
    <div class="row my-4 justify-content-between">
        
        <div class="col-4">
            <h1 class="titulo-seccion">Lista de Categorias</h1>
        </div>
        
        <div class="col-4">
            <%= link_to admin_nueva_categoria_path, class:"btn btn-primary boton-izquierda" do %>
                <i class="bi bi-plus-circle"></i>
                Crear Nueva Categoría
            <% end %>
            <%= link_to admin_productos_path, class:"btn btn-primary boton-derecha" do %>
                <i class="bi bi-card-list"></i>
                Lista Productos
            <% end %>
        </div>
    </div>
    <div class="row my-2 justify-content-between">
        <div class="col-4">
            <h3>Nombre</h3>
        </div>
        <div class="col-2 me-4">
            <h3>Acciones</h3>
        </div>
    </div>
    <% @lista_categorias.each do |categoria| %>
        <div class="row my-3 justify-content-between border border-2 border-primary rounded-pill shadow rounded hover filas-lista-categorias">
            <div class="col-4 ms-3 my-auto fw-bolder fs-5"><%= categoria.categoria %></div>
            <div class="col-2  p-0 mx-0 my-1">
                <%= link_to admin_editar_categorias_path(categoria), class:"btn btn-warning boton-izquierda" do %>
                    <i class="bi bi-pencil-fill"></i>
                    Editar
                <% end %>
                <%= link_to admin_categoria_path(categoria), method: :delete, data: { confirm: '¿Quieres eliminar la categoria?' }, class:"btn btn-danger boton-derecha" do %>                   
                    <i class="bi bi-trash-fill"></i>
                    Eliminar                    
                <% end %>
            </div>
        </div>
    <% end %>

app/views/admin/categorias/mostrar.html.erb
<%= @categoria.categoria %>
<%= link_to 'Ver categorias', admin_categorias_path %>